### ISSUE TITLE
new package.json handling

### ISSUE THREAD

**Issue by guybedford** [matthewp/jspm-bower#2]
I've updated the package.json dependency handling in line with what we discussed previously - jspm now automatically translates the "dependencies" part from other registries, as indicated by the package.json "registry" property.

For example, here is the new version of jspm-npm - https://github.com/jspm/npm/blob/master/npm.js#L159

It would be good to update this to reflect the change. Happy to submit a PR as well.

**Comment by matthewp** [comment]
My memories a little foggy, would you mind submitting a PR this time?

**Comment by guybedford** [comment]
Sure, will look into it when I can.
